<?php 


$age = array(
            'ARS' => 'Argentina Peso',
            'AED' => 'United Arab Emirates Dirham',
            'AUD' => 'Australia Dollar',
            'BSD' => 'Bahamas Dollar',
            'BGN' => 'Bulgaria Lev',
            'BRL' => 'Brazil Real',
            'CAD' => 'Canada Dollar',
            'CLP' => 'Chile Peso',
            'CNY' => 'China Yuan Renminbi',
            'COP' => 'Colombia Peso',
            'HRK' => 'Croatia Kuna',
            'CZK' => 'Czech Republic Koruna',
            'DKK' => 'Denmark Krone',
            'DOP' => 'Dominican Republic Peso',
            'EGP' => 'Egypt Pound',
            'EUR' => 'Euro Member Countries',
            'FJD' => 'Fiji Dollar',
            'GTQ' => 'Guatemala Quetzal',
            'HKD' => 'Hong Kong Dollar',
            'HUF' => 'Hungary Forint',
            'ISK' => 'Iceland Krona',
            'INR' => 'India Rupee',
            'IDR' => 'Indonesia Rupiah',
            'ILS' => 'Israel Shekel',
            'JPY' => 'Japan Yen',
            'KZT' => 'Kazakhstan Tenge',
            'KRW' => 'Korea (South) Won',
            'MYR' => 'Malaysia Ringgit',
            'MXN' => 'Mexico Peso',
            'NZD' => 'New Zealand Dollar',
            'NOK' => 'Norway Krone',
            'PKR' => 'Pakistan Rupee',
            'PAB' => 'Panama Balboa',
            'PYG' => 'Paraguay Guarani',
            'PEN' => 'Peru Nuevo Sol',
            'PHP' => 'Philippines Peso',
            'PLN' => 'Poland Zloty',
            'RON' => 'Romania New Leu',
            'RUB' => 'Russia Ruble',
            'SAR' => 'Saudi Arabia Riyal',
            'SGD' => 'Singapore Dollar',
            'ZAR' => 'South Africa Rand',
            'SEK' => 'Sweden Krona',
            'CHF' => 'Switzerland Franc',
            'TWD' => 'Taiwan New Dollar',
            'THB' => 'Thailand Baht',
            'TRY' => 'Turkey Lira',
            'UAH' => 'Ukraine Hryvna',
            'GBP' => 'United Kingdom Pound',
            'USD' => 'United States Dollar',
            'UYU' => 'Uruguay Peso',
            'VND' => 'Viet Nam Dong',
);

$symbol = array(
    "ARS" => "ARS $",
    "ZAR" => "R",
    "UAH" => "₴",
     "AED" => "د.إ",
    "AUD" => "AUD $",
    "BSD" => "BSD $",
    "HRK" => "kn",
    "UYU" => "UYU $",
    "COP" => "COP $",
    "FJD" => "FJD $",
    "GTQ" => "Q",
    "DOP" => "DOP $",
    "ISK" => "kr",
    "PAB" => "B/.",
    "PYG" => "₲",
    "PEN" => "S/",
    "RON" => "lei",
    "IDR" => "Rp",
    "EGP" => "E£",
    "CNY" => "¥",
    "BGN" => "Лв.",
    "CLP" => "CLP $",
    "SGD" => "SGD $",
    "BRL" => "BRL $" , 
    "SAR" => "SR" , 
    "RUB" => "RUB",
    "BDT" => "৳", //Bangladeshi Taka
    "CAD" => "CAD $" , //Canadian Dollar
    "CHF" => "Fr" , //Swiss Franc
    "CRC" => "₡", //Costa Rican Colon
    "CZK" => "Kč" , //Czech Koruna
    "DKK" => "Kr." , //Danish Krone
    "EUR" => "€" , //Euro
    "GBP" => "£" , //Pound Sterling
    "HKD" => "HKD $" , //Hong Kong Dollar
    "HUF" => "Ft" , //Hungarian Forint
    "ILS" => "₪" , //Israeli New Sheqel
    "INR" => "INR", //Indian Rupee
    "JPY" => "¥" , //also use ¥ Japanese Yen
    "KZT" => "₸", //Kazakhstan Tenge
    "KRW" => "₩",   //Korean Won
    "KHR" => "៛", //Cambodia Kampuchean Riel    
    "MYR" => "RM" , //Malaysian Ringgit 
    "MXN" => "MXN $" , //Mexican Peso
    "NOK" => "kr" , //Norwegian Krone
    "NGN" => "₦",   //Nigerian Naira
    "NZD" => "NZD $" , //New Zealand Dollar
    "PHP" => "₱" , //Philippine Peso
    "PKR" => "₨" , //Pakistani Rupees
    "PLN" => "zł" ,//Polish Zloty
    "SEK" => "kr" , //Swedish Krona 
    "TWD" => "TWD $" , //Taiwan New Dollar 
    "THB" => "฿" , //Thai Baht
    "TRY" => "TRY", //Turkish Lira
    "USD" => "USD $" , //U.S. Dollar
    "VND" => "₫"    //Vietnamese Dong
    );

// $symbol = array(
//     "ARS" => "$",
//     "ZAR" => "R",
//     "UAH" => "₴",
//      "AED" => "د.إ",
//     "AUD" => "A$",
//     "BSD" => "B$",
//     "HRK" => "kn",
//     "UYU" => "$U",
//     "COP" => "$",
//     "FJD" => "FJ$",
//     "GTQ" => "Q",
//     "DOP" => "RD$",
//     "ISK" => "kr",
//     "PAB" => "B/.",
//     "PYG" => "₲",
//     "PEN" => "S/",
//     "RON" => "lei",
//     "IDR" => "Rp",
//     "EGP" => "E£",
//     "CNY" => "¥",
//     "BGN" => "Лв.",
//     "CLP" => "$",
//     "SGD" => "S$",
//     "BRL" => "R$" , 
//     "SAR" => "SR" , 
//     "RUB" => "₽",
//     "BDT" => "৳", //Bangladeshi Taka
//     "CAD" => "C$" , //Canadian Dollar
//     "CHF" => "Fr" , //Swiss Franc
//     "CRC" => "₡", //Costa Rican Colon
//     "CZK" => "Kč" , //Czech Koruna
//     "DKK" => "Kr." , //Danish Krone
//     "EUR" => "€" , //Euro
//     "GBP" => "£" , //Pound Sterling
//     "HKD" => "HK$" , //Hong Kong Dollar
//     "HUF" => "Ft" , //Hungarian Forint
//     "ILS" => "₪" , //Israeli New Sheqel
//     "INR" => "₹", //Indian Rupee
//     "JPY" => "¥" , //also use ¥ Japanese Yen
//     "KZT" => "₸", //Kazakhstan Tenge
//     "KRW" => "₩",   //Korean Won
//     "KHR" => "៛", //Cambodia Kampuchean Riel    
//     "MYR" => "RM" , //Malaysian Ringgit 
//     "MXN" => "Mex$" , //Mexican Peso
//     "NOK" => "kr" , //Norwegian Krone
//     "NGN" => "₦",   //Nigerian Naira
//     "NZD" => "$" , //New Zealand Dollar
//     "PHP" => "₱" , //Philippine Peso
//     "PKR" => "₨" , //Pakistani Rupees
//     "PLN" => "zł" ,//Polish Zloty
//     "SEK" => "kr" , //Swedish Krona 
//     "TWD" => "NT$" , //Taiwan New Dollar 
//     "THB" => "฿" , //Thai Baht
//     "TRY" => "₺", //Turkish Lira
//     "USD" => "$" , //U.S. Dollar
//     "VND" => "₫"    //Vietnamese Dong
//     );
?>