<?php include APPPATH.'views/frontend/includes/header.php'; ?>

<div class="common-innerdiv">
	<div class="container">
		<h1 class="text-center"><span>Terms and Conditions</span></h1>
		<div class="mw-privacypolicy">
			<p>Welcome to Mawjuud, operated by Mawjuud, Inc. Mawjuud, Inc. is a part of Mawjuud, Inc By using Mawjuud’s Web sites (defined to include all properties (mobile, Web or otherwise) owned and operated by Mawjuud), related data, and/or related services (collectively, “Services”), you agree to be bound by the following terms of use, as updated from time to time (“Terms of Use”).</p>

			<h4>General</h4>
			<ul>
				<li>Any dispute or claim arising out of or in connection with this website shall be governed and construed in accordance with the laws of UAE.</li>
				<li>United Arab of Emirates is our country of domicile.</li>
				<li>Minors under the age of 18 shall are prohibited to register as a User of this website and are not allowed to transact or use the website.</li>
				<li>If you make a payment for our products or services on our website, the details you are asked to submit will be provided directly to our payment provider via a secured connection.</li>
				<li>The cardholder must retain a copy of transaction records and Merchant policies and rules</li>
			</ul>

			<h4>Permissible Use.</h4>
			<p>Unless you are a real estate or lending professional acting in your professional capacity, you agree to use the Services for your personal use, and your commercial use is limited to transactions done on your own behalf. The commercial use of real estate and lending professionals is limited to providing information to consumers via the Services or, where authorized, taking actions on behalf of a consumer client (e.g., post a home for sale). Without limitation, lending professionals and institutions are prohibited from using information provided by Mawjuud through the Services in making any loan-related decisions. The Services may be used only for transactions in residential real estate and may not be used for transactions in commercial real estate, which includes, without limitation, commercially zoned properties, timeshares, and vacation rentals. Subject to the restrictions set forth in the following paragraphs, you may copy information from the Services only as necessary for your personal use to view, save, print, fax and/or e-mail such information. You agree otherwise not to reproduce, modify, distribute, display or otherwise provide access to, create derivative works from, decompile, disassemble or reverse engineer any portion of the Services. In addition, you agree not to provide/post/authorize a link to any of the Services (including but not limited to your agent profile page) from a third party website that is not a real estate related website owned or operated by a real estate or lending professional or institution. Notwithstanding the foregoing, the aggregate level data provided on the Mawjuud Local-Info Pages, and available at http://www.Mawjuud.com, (the “Aggregate Data”) may be used for non-personal uses, e.g., real estate market analysis. You may display and distribute derivative works of the Aggregate Data (e.g., within a graph), so long as Mawjuud is cited as a source.</p>


			<h4>Restrictions and Additional Terms.</h4>
			<p>You agree not to remove or modify any copyright or other intellectual property notices that appear in the Services. You will not use the Services for resale, service bureau, time-sharing or other similar purposes. Further:</p>
			<ul>
				<li>Acceptable Use. You agree not to use the Services in any way that is unlawful, or harms Mawjuud, its service providers, suppliers or any other user. You agree not to use the Services in any way that breaches the Mawjuud Rentals Terms or any other policy or notice on the Services. You agree not to distribute or post spam, chain letters, pyramid schemes, or similar communications through the Services. You agree not to impersonate another person or misrepresent your affiliation with another person or entity. Except as expressly stated herein, these Terms of Use do not provide you a license to use, reproduce, distribute, display or provide access to any portion of the Services on third-party Web sites or otherwise. Except as expressly stated herein and without limitation, you agree that you will not, nor will you permit or encourage any third party to, reproduce, publicly display, or otherwise make accessible on or through any other Web site, application, or service any reviews, ratings, and/or profile information about real estate, lending, or other professionals, underlying images of or information about real estate listings, or other data or content available through the Services.</li>
				<li>Automated Queries. Automated queries (including screen and database scraping, spiders, robots, crawlers and any other automated activity with the purpose of obtaining information from the Services) are strictly prohibited on the Services, unless you have received express written permission from Mawjuud. As a limited exception, publicly available search engines and similar Internet navigation tools (“Search Engines”) may query the Services and provide an index with links to the Services’ Web pages, only to the extent such unlicensed “fair use” is allowed by applicable copyright law. Search Engines are not permitted to query or search information protected by a security verification system (“captcha”) which limits access to human users.</li>
				<li>Windows Live Virtual Earth. Windows Live Virtual Earth imagery is supplied by Microsoft Corporation, and use is subject to the Microsoft MapPoint Terms of Use, located at http://www.microsoft.com/maps/assets/docs/terms.aspx.</li>
				<li>Google Maps. Some of the Services implement the Google Maps web mapping service. Your use of Google Maps is subject to Google’s terms of use, located at http://www.google.com/intl/en_us/help/terms_maps.html</li>
				<li>Calls. If you, as a consumer, choose to contact a real estate agent or a Lender (as defined below) through the Services by filling out a contact or other request form on the Services, you authorize Mawjuud to provide your name and contact information and other identifying information you provide to the applicable real estate agent or Lender. You acknowledge that, by submitting your contact request or other request form on the Services or by electing to request pre-approval, you may receive telemarketing calls from or on behalf of the real estate agent or Lender at the telephone number(s) you provide.
The Services may provide phone numbers that can connect you with Mawjuud, its service providers, or other third parties, such as real estate agents and Lenders. Some of the numbers listed may be routed through a third party service (“Calling Service”). Calls through the Calling Service may be recorded or monitored for quality assurance and customer service purposes. In the event that you make a call to Mawjuud or through a Calling Service, you consent to such recording and monitoring. Mawjuud will treat recorded calls in accordance with its Privacy Policy.</li>
			</ul>


			<h4>Materials You Provide; Account Use; Privacy; </h4>
			<p>Third Party Web Sites. For materials you post or otherwise provide to Mawjuud in connection with the Services (your “Submission”), you grant Mawjuud an irrevocable, perpetual, royalty-free worldwide license to (a) use, copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, modify, prepare derivative works of or incorporate into other works, and translate your Submission, in connection with the Services or in any other media, and (b) sublicense these rights, to the maximum extent permitted by applicable law. Mawjuud will not pay you for your Submission or to exercise any rights related to your Submission set forth in the preceding sentence. Mawjuud may remove or modify your Submission at any time. For each Submission, you agree to provide accurate and complete information and represent that you have all rights necessary to grant Mawjuud the rights in this paragraph, that Mawjuud ‘s use of the Submission will not infringe any third party rights and that the Submission complies with Section 2(a) above. You are solely responsible for all Submissions made through your user account(s) on the Services or that you otherwise make available through the Services.</p>
			<p>Mawjuud will not use client contact information that is uploaded by agents into the Mawjuud Agent Hub portal for any purpose.</p>

			<p>You may not share your user account(s) with others. You are responsible for all actions taken via your account. Mawjuud will treat your use of the Services in accordance with its Privacy Policy. Certain Mawjuud functionalities may involve the distribution of your Submission to third party Web sites over which Mawjuud has no control. Mawjuud is not responsible for and makes no warranties or representations pertaining to these third party Web sites, including but not limited to the content, availability, or functionality of such Web sites. You are responsible for ensuring that your Submission complies with the terms of use associated with any such third party Web site and you understand that your Submission and your use of a third party Web site will be treated in accordance with that third party Web site’s own privacy policy.</p>


			<h4>Advertising</h4>
			<p>Mawjuud’s business is primarily funded through advertising. You understand and agree that the Services may include advertisements, and that these are necessary to support the Services. To help make the advertisements relevant and useful to you, Mawjuud may serve advertisements based on the information we collect from you or in relation to your interaction on our site. See the Privacy Policy for more details. In the event that you have entered into a separate agreement (“Diverse Solutions Agreement”) with Mawjuud under which you are granted the right to use certain of Mawjuud ‘s Diverse Solutions products (the “Diverse Solutions Products”), Mawjuud will not serve advertising on the Diverse Solutions Products unless otherwise provided in the Diverse Solutions Agreement.</p>

			<h4>The Role of Mawjuud</h4>
			<p> is a licensed real estate broker in the city of Dubai but does not broker real estate transactions. Mawjuud does not act as a real estate agent for you or any other user. Mawjuud does not sell, buy, or negotiate the purchase, sale, or exchange of real property. Further, Mawjuud does not lease or rent, offer to lease or rent, or negotiate the lease of real property or otherwise aid or assist in the lease of real property.</p>


			<h4>Mawjuud allows </h4>
			<p>consumers to provide anonymous information to banks, lenders, financial institutions, originators, loan brokers, other mortgage professionals and their employees (collectively, the “Lenders”) to request quotes on terms for home loans. Lenders may elect to respond to consumer requests with non-binding customized quotes of the terms they would offer to a borrower fitting the consumer’s anonymous profile, as well as their contact information. These non-binding quotes are not intended to be official Loan Estimates as defined in the Real Estate Settlement Procedures Act.</p>

			<h4>Mawjuud, also allows </h4>
			<p>consumers to provide certain information to Lenders and receive Lender contact information or request that Lenders pre-approve them for home loans. Mawjuud does NOT take mortgage applications. Mawjuud does NOT make loans or credit decisions in connection with loans. Any loan inquiry you submit is NOT an application for credit. Mawjuud does not pre-approve borrowers for loans. Mawjuud lists Lenders who may conduct a preliminary review to determine your loan qualifications based on their guidelines.</p>

			<h4>To receive a pre-approval letter,</h4>
			<p>you must complete a short online questionnaire that asks for personal information including income, credit score, and monthly debt. After completing the questionnaire, you may see an estimated pre-approval amount based on the information you provided. To continue the process of requesting a pre-approval letter, a Lender will require more details, such as pulling your credit report (at your request). If you meet the Lender’s guidelines based on preliminary review of your responses to the questionnaire and your credit report, you may receive an online pre-approval letter. A pre-approval letter is not an offer to lend, a commitment to make a loan, or a guarantee of specific rates or terms. Even if you receive a pre-approval letter, you may not get a loan from a Lender or a loan at a specific rate or subject to particular terms. A Lender may require income and asset verification, as well as satisfaction of other conditions, before they commit to extending a loan. Mawjuud does not guarantee acceptance into any particular loan program or specific loan terms or conditions with any Lender—loan approval standards are established and maintained solely by individual Lenders. Mawjuud does not guarantee that the loan terms or rates offered and made available by Lenders are the best terms or lowest rates available in the market. When consumers submit the required information for a Lender to contact them or when consumers request pre-approval from a participating Lender, Lenders may elect to respond based on parameters established by the Lender and Mawjuud will create a contact for the selected Lender based on parameters established by the Lender. If you, as a consumer, choose to contact a Lender through the Services offered by Mawjuud by filling out a contact request or other request form or by completing a questionnaire on websites associated with these Services, you authorize Mawjuud to provide your name, contact information and other information you provide to a Lender, along with your quote or pre-approval request (if any). You acknowledge that, by submitting your contact request, other request form or by completing a questionnaire on the Services, you may receive telemarketing calls from or on behalf of a Lender at the telephone number(s) you provide. By submitting your name, contact information and other information, your identity will no longer be anonymous. Any loan or other business conducted is between you and the Lender. By submitting personal information through Services offered through Mawjuud you authorize, Lenders (or a third party designated by a Lender) to request from one or multiple credit bureaus / reporting agencies, your credit bureau report including any ancillary credit scores or ratings.</p>

			<h4> Disclaimer Mawjuud</h4>
			<p> is not a Lender, loan originator, loan processor, or underwriter. Mawjuud does not aid or assist borrowers in obtaining loans, solicit borrowers or Lenders for loans, offer or negotiate terms of loans, or make loans or credit decisions in connection with loans. Mawjuud does not take applications for credit or issue pre-approval letters. Your submission of information and any request for quotes or pre-approval is not an application for credit. Mawjuud does not endorse, refer or recommend any Lender or the products of any Lender. Consumers should rely on their own judgment in deciding which available loan product, terms and Lender best suit their needs and financial means. Nothing contained in the Services is an offer to lend or a commitment for a loan, and Mawjuud does not guarantee any specific loan terms and conditions offered to consumers by a Lender will be granted, or that consumers will be offered any type of loan by any Lender. Mawjuud is not an agent of either any consumer or any Lender. Mawjuud is only providing an administrative service to consumers and participating Lenders. Decisions regarding Lenders contacting consumers or pre-approval requests are made by participating Lenders and not Mawjuud. Mawjuud assumes no responsibility for any result or consequence related directly or indirectly to any action or inaction that consumers take based on the Services, including Mawjuud , and any other information available there. Interest rates provided through the Services are for information purposes only, and actual interest rates may vary. Lenders may keep consumer loan request information and any other information provided by Mawjuud or received by Lenders in processing a contact or pre-approval request, whether or not a consumer is qualified for a loan with a Lender.</p>


			<h4>  Fees:</h4>
			<p> The Services offered by Mawjuud are free to consumers. Mawjuud a wholly owned subsidiary of Mawjuud is paid an advertising fee by Lenders for the goods, facilities and services provided through the Services offered by Mawjuud.</p>

			<h4>Participating Lenders:</h4>
			<p>The Lenders participating on the Services are solely responsible for their services to consumers. Mawjuud shall not be liable for any damages or costs of any type arising out of or in any way connected with any consumers’ use of the Services or the services offered by Lenders. Mawjuud is not responsible for any errors or delays caused by consumers or any Lenders in the loan process. Mawjuud reserves the right, at any time and in its sole discretion, to discontinue, suspend, or terminate the participation of any Lender or other user from using or participating in any of the Services offered by Mawjuud.</p>

			<h4>Privacy:</h4>
			<p>Mawjuud may use personally identifying information provided by a consumer to improve the relevance of advertising shown to consumers. Please consult the Privacy Policy for more information.</p>

			<h4>Lender Terms:</h4>
			<p>Lenders participating in Services offered by Mawjuud are further subject to the Mawjuud Terms of Use.</p>
			<p> Licenses: Mawjuud is a wholly-owned subsidiary of Mawjuud and has its headquarters at DUBAI – United Arab Emirates</p>
			<ul>
				<li>Disclosures and Consent: By using this website and Services, the disclosures and consent required under certain state laws are deemed to be provided, received, and agreed to.</li>
			</ul>

			<h4>Linked Materials and Third-Party Materials</h4>
			<p>The Services include links to third-party products, services and Web sites, as well as materials provided by third parties. Mawjuud does not endorse, and takes no responsibility for such products, services, Web sites, and materials. You understand that Mawjuud has no obligation to, and generally does not, approve or monitor materials provided by third parties through the Services. Your dealings with any third party arising in connection with the Services are solely between you and such third party, and Mawjuud takes no responsibility for any damages or costs of any type arising out of or in any way connected with your dealings with these third parties.</p>


			<h4>Claims of Copyright Infringement:</h4>
			<p>Mawjuud respects the intellectual property rights of others, and asks that everyone using the Services do the same. Anyone who believes that their work has been reproduced on the Services in a way that constitutes copyright infringement may notify Mawjuud ‘s by providing the following information:</p>

			<ul>
				<li>
					 Identification of the copyrighted work that you claim has been infringed;
				</li>
				<li>Identification of the material that you claim is infringing and needs to be removed, including a description of where it is located on the Services so that the copyright agent can locate it;</li>
				<li>Your address, telephone number, and, if available, e-mail address, so that the copyright agent may contact you about your complaint; and</li>
				<li>A signed statement that the above information is accurate; that you have a good faith belief that the identified use of the material is not authorized by the copyright owner, its agent, or the law; and, under penalty of perjury, that you are the copyright owner or are authorized to act on the copyright owner’s behalf in this situation.
				<p><b>Notices of copyright infringement claims should be sent as follows:</b> If you give notice of copyright infringement by text e-mail, we may begin investigating the alleged copyright infringement; however, we must receive your signed statement by mail or as an attachment to your e-mail before we are required to take any action.</p>
				</li>
				<li>Intellectual Property: The Services are the property of Mawjuud, and subject to the intellectual property rights of Mawjuud and its licensors. You may not use any of Mawjuud’s trademarks as part of your screen name or email address on the Services. The names of actual companies, products, and services mentioned herein may be the trademarks of their respective owners. Any rights not expressly granted herein are reserved. <p>Mawjuud does not assert copyright or grant any rights to the underlying images or descriptions of real estate listings provided through the Services. Any use of these images and descriptions is subject to the copyright owner’s permission and/or the requirements of applicable law.</p></li>

				<li>no warranty. mawjuud provides the services “as is,” “with all faults” and “as available,” and the entire risk as to satisfactory quality, performance, accuracy, and effort is with you. to the maximum extent permitted by applicable law, mawjuud and its suppliers make no representations, warranties or conditions, express or implied. mawjuud and its suppliers expressly disclaim any and all warranties or conditions, express, statutory and implied, including without limitation (a) warranties or conditions of merchantability, fitness for a particular purpose, workmanlike effort, accuracy, title, quiet enjoyment, no encumbrances, no liens and non-infringement, (b) warranties or conditions arising through course of dealing or usage of trade, and (c) warranties or conditions of uninterrupted or error-free access or use.</li>
				<li>liability limitation; exclusive remedy. in no event will mawjuud or any supplier be liable for any damages, including without limitation any indirect, consequential, special, incidental, or punitive damages arising out of, based on, or resulting from these terms of use or your use of the services, even if such party has been advised of the possibility of such damages. the exclusion of damages under this paragraph is independent of your exclusive remedy set forth below and survives in the event such remedy fails of its essential purpose or is otherwise deemed unenforceable. these limitations and exclusions apply without regard to whether the damages arise from (a) breach of contract, (b) breach of warranty, (c) negligence, or (d) any other cause of action, to the extent such exclusion and limitations are not prohibited by applicable law. if you do not agree with any part of these terms of use, or you have any dispute or claim against mawjuud or its suppliers with respect to these terms of use or the services, then you’re sole and exclusive remedy is to discontinue using the services.</li>
				<li>Changes; Discontinuance. Mawjuud reserves the right to change these Terms of Use at any time in its sole discretion. Any changes will be effective immediately upon posting the revised version of these Terms of Use to Mawjuud’s properties. Your continued use of the Services after the effectiveness of such changes will constitute acceptance of and agreement to any such changes. You further waive any right you may have to receive specific notice of such changes to these Terms of Use. You are responsible for regularly reviewing these Terms of Use. Mawjuud may alter, suspend or discontinue the Services at any time to you and/or to others, without notice.</li>
				<li>Choice of Law; Disputes. These Terms of Use are governed by the laws of the United Arab Emirates, without giving effect to its conflict of law’s provisions. You agree to submit to exclusive jurisdiction and venue in the state and federal courts sitting in for any and all disputes, claims and actions arising from or in connection with the Services and/or these Terms of Use. In any dispute arising under this Agreement, the prevailing party will be entitled to attorneys’ fees and expenses.</li>
				<li>Indemnification: You agree to defend and hold Mawjuud, its affiliates, and their respective directors, officers, employees, and agents harmless from any and all claims and demands made by any third party due to or arising out of your breach of these Terms of Use, your use of the Services, your violation of any law or the rights of a third party, or any Submission made through your user account on the Services or that you otherwise make available through the Services.</li>
				<li>Release: You release Mawjuud , its affiliates, and their respective directors, officers, employees and agents from all liability related to any and all claims and demands you may assert against any third party arising out of the Services. If you are a</li>
				<li>General: You agree not to export from anywhere any part of the Services provided to you or any direct product thereof except in compliance with, and with all licenses and approvals required under, applicable export laws, rules and regulations. All Services used by the Government are provided with the commercial license rights described herein. If any part of these Terms of Use is determined to be invalid or unenforceable, then the invalid or unenforceable provision will be replaced with a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of these Terms of Use will continue in effect. The section titles in these Terms of Use are solely used for the convenience of the parties and have no legal or contractual significance. Mawjuud may assign this Agreement, in whole or in part, at any time with or without notice to you. You may not assign these Terms of Use, or assign, transfer or sublicense your rights, if any, in the Service. Mawjuud’s failure to act with respect to a breach by you or others does not waive its right to act with respect to subsequent or similar breaches. Except as expressly stated herein, these Terms of Use constitute the entire agreement between you and Mawjuud with respect to the Services and supersede all prior or contemporaneous communications of any kind between you and Mawjuud with respect to the Services.</li>
			</ul>



		</div>
	</div>
</div>

<?php include APPPATH.'views/frontend/includes/footer.php'; ?>
<?php include APPPATH.'views/frontend/includes/footer_script.php'; ?>